apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: controller
  name: controller
  namespace: cellery-system
spec:
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: controller
    spec:
      containers:
      - image: wso2cellery/mesh-controller:0.2.0
        imagePullPolicy: Always
        name: controller
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      serviceAccount: controller
      serviceAccountName: controller
